services:
  - type: web
    name: language-crm-backend
    env: node
    plan: free
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_TOKEN_KEY
        sync: false
      - key: REFRESH_TOKEN_KEY
        sync: false
      - key: ADMIN_ACCESS_TOKEN_KEY
        sync: false
      - key: ADMIN_REFRESH_TOKEN_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ACCESS_TOKEN_TIME
        sync: false
      - key: REFRESH_TOKEN_TIME
        sync: false
      - key: COOKIE_TIME
        sync: false
      - key: ADMIN_ACCESS_TOKEN_TIME
        sync: false
      - key: ADMIN_REFRESH_TOKEN_TIME
        sync: false
      - key: ADMIN_COOKIE_TIME
        sync: false
      - key: SMS_TOKEN
        sync: false
      - key: SMS_SERVICE_URL
        sync: false
      - key: SMS_TEMPLATE
        sync: false
