services:
  - type: web
    name: language-crm-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
